name: kazahana
description: Kazahana
version: 1.0.14-beta.0

publish_to: none

environment:
    sdk: ">=2.15.0-226.0.dev <3.0.0"

dependencies:
    animations: ^2.0.1
    archive: ^3.1.5
    better_player: ^0.0.79
    clipboard: ^0.1.3
    collection: ^1.15.0
    crypto: ^3.0.1
    dart_vlc: ^0.1.8
    flutter:
        sdk: flutter
    flutter_markdown: ^0.6.6
    fuzzy: ^0.4.0-nullsafety.0
    html: ^0.15.0
    http: ^0.13.3
    json_annotation: ^4.4.0
    objectbox: ^1.2.0
    objectbox_flutter_libs: any
    ota_update: ^3.1.1
    package_info_plus: ^1.0.5
    path: ^1.8.0
    path_provider: ^2.0.2
    protocol_registry: ^0.0.5
    shelf: ^1.2.0
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    uni_links: ^0.5.1
    url_launcher: ^6.0.9
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx
    utilx_desktop:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx_desktop
    utilx_mobile:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx_mobile
    version: ^2.0.0
    wakelock: ^0.5.6
    window_manager: ^0.1.4

dev_dependencies:
    build_runner: ^2.0.5
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
    json_serializable: ^6.1.1
    lint: ^1.5.3
    objectbox_generator: any

flutter:
    uses-material-design: true
    assets:
        - assets/data/
        - assets/images/
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Italic.ttf
                style: italic
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 800
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
