name: utilx
description: Custom utility package for Yukino
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    devx:
        path: ../devx
    lint: ^1.5.3

flutter:
    plugin:
        platforms:
            windows:
                pluginClass: UtilxPlugin
